# Generated by Django 6.0.2 on 2026-04-10 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='population',
        ),
        migrations.AddField(
            model_name='village',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='leader_name',
            field=models.CharField(default='', max_length=50, verbose_name='이장님 성함'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='village',
            name='address',
            field=models.CharField(max_length=255, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, verbose_name='마을명'),
        ),
    ]
