# Generated by Django 6.0.2 on 2026-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20, verbose_name='그룹코드')),
                ('code', models.CharField(max_length=20, verbose_name='상세코드')),
                ('code_name', models.CharField(max_length=100, verbose_name='코드명')),
                ('is_use', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='설정 키')),
                ('value', models.TextField(verbose_name='설정 값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정 목록',
            },
        ),
    ]
