# Generated by Django 4.2.13 on 2026-04-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCodeMas',
            fields=[
                ('master_cd', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='대분류 코드')),
                ('master_nm', models.CharField(max_length=100, verbose_name='대분류명')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '공통코드 대분류',
                'verbose_name_plural': '공통코드 대분류',
                'db_table': 'sy_comcode_bas',
            },
        ),
        migrations.AlterField(
            model_name='commoncode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CommonCodeDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtl_cd', models.CharField(max_length=20, verbose_name='소분류 코드')),
                ('dtl_nm', models.CharField(max_length=100, verbose_name='소분류명')),
                ('sort_ord', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('master_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.commoncodemas', verbose_name='대분류 코드')),
            ],
            options={
                'verbose_name': '공통코드 소분류',
                'verbose_name_plural': '공통코드 소분류',
                'db_table': 'sy_comcode_dtl',
                'ordering': ['sort_ord'],
                'unique_together': {('master_cd', 'dtl_cd')},
            },
        ),
    ]
