# Generated by Django 4.2.13 on 2026-04-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_commoncodemas_alter_commoncode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncodedtl',
            name='master_cd',
            field=models.ForeignKey(db_column='master_cd', on_delete=django.db.models.deletion.CASCADE, to='system.commoncodemas', verbose_name='대분류 코드'),
        ),
    ]
