# Generated by Django 5.2.13 on 2026-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_commoncodedtl_master_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncodedtl',
            name='id',
        ),
        migrations.AddField(
            model_name='commoncodedtl',
            name='dtl_idx',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='소분류 PK'),
        ),
        migrations.AddField(
            model_name='commoncodemas',
            name='remarks',
            field=models.TextField(blank=True, db_column='remarks', null=True),
        ),
    ]
