# Generated by Django 5.2.13 on 2026-05-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_commoncodedtl_id_commoncodedtl_dtl_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commoncodedtl',
            table='sys_comcode_dtl',
        ),
        migrations.AlterModelTable(
            name='commoncodemas',
            table='sys_comcode_bas',
        ),
    ]
