# Generated by Django 5.2.13 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_commoncodedtl_table_alter_commoncodemas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoncodedtl',
            options={'managed': False, 'ordering': ['sort_ord'], 'verbose_name': '공통코드 소분류', 'verbose_name_plural': '공통코드 소분류'},
        ),
        migrations.AlterModelOptions(
            name='commoncodemas',
            options={'managed': False, 'verbose_name': '공통코드 대분류', 'verbose_name_plural': '공통코드 대분류'},
        ),
        migrations.AlterField(
            model_name='commoncode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
