# Generated by Django 6.0.2 on 2026-04-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village', '0002_remove_village_population_village_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='업무/활동명')),
                ('content', models.TextField(verbose_name='상세 내용')),
                ('work_date', models.DateField(verbose_name='활동 일자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village', verbose_name='해당 마을')),
            ],
            options={
                'verbose_name': '마을 업무',
                'verbose_name_plural': '마을 업무 목록',
            },
        ),
    ]
