# Generated by Django 5.2.13 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_villagework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
