# Generated by Django 6.0.2 on 2026-04-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village', '0002_remove_village_population_village_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='지원 사업명')),
                ('amount', models.IntegerField(verbose_name='지원 금액')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('target_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village', verbose_name='대상 마을')),
            ],
        ),
    ]
