# Generated by Django 5.2.13 on 2026-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
